### PR TITLE
Completed T015 and T034 for US005

### PR DESCRIPTION
**Pull request by aminahaq305**
I have added the functionality to add text to the existing pdf in order to annotate it. I will add Doxygen formatted comments in the last sprint. Screenshots are attached and the pdf files are in the appropriate directory on Github. The text color can be changed, I made it yellow for now to ensure the difference between existing text and new text.
proof
proof2

### CODE REVIEW

**Review by paulinearcita — COMMENTED** [review]
This looks good to me! Just remember to add Doxygen formatting next time and proof of execution in our TestResults folder.

**Review by priyap2021 — COMMENTED** [review]
This looks perfect to me. Just add the deoxygen formatting in your last sprint.

**Comment by aminahaq305** [comment]
> This looks good to me! Just remember to add Doxygen formatting next time and proof of execution in our TestResults folder.

I have already added the files to the TestResults folder. And like I said in the comment I will add comments in the last sprint.

**Review by hazejjk — APPROVED** [review]
Looks good to me! Good work.

**Review by joshkettlehake — APPROVED** [review]
I cannot see boxes 2 and 3 after this. It says the file has been deleted. I'm assuming they were screenshots. The rest of this looks good. Removed the unnecessary imports, and opened up the variable to determine the file to be used.

**Pull request merged**
