### PR TITLE
Proof of US016 Completion

### PR DESCRIPTION
**Pull request by paulinearcita**

### CODE REVIEW

**Review by aminahaq305 — COMMENTED** [review]
I downloaded the ppt file and viewed it in powerpoint. It looks like the slide is just a skewed image of the png. I have attached a screenshot for reference. If this is what you were going for then I approve the changes.
Also thank you for uploading the proof in the appropriate directory
Screen Shot 2021-04-01 at 9 31 27 PM

**Review by priyap2021 — CHANGES_REQUESTED** [review]
This looks good to me. Thank you for the proofs.

**Comment by paulinearcita** [comment]
> I downloaded the ppt file and viewed it in powerpoint. It looks like the slide is just a skewed image of the png. I have attached a screenshot for reference. If this is what you were going for then I approve the changes.
> Also thank you for uploading the proof in the appropriate directory
> Screen Shot 2021-04-01 at 9 31 27 PM

At the moment, yes. The goal for the user story was to convert the page to a photo and attach it in slides. I can keep in mind to make it look better for future development. Thanks for the feedback!

**Review by hazejjk — APPROVED** [review]
Looks good to me. Good work Pauline! Merging them now.

**Pull request merged**
