### PR TITLE
Completed T038 for US018

### PR DESCRIPTION
**Pull request by aminahaq305**
Uploaded a Doxyfile that outlines the settings that will be used to produce the documentation using Doxygen. As per Prof. Buck's email reply we do not have to upload the HTML files produced by Doxygen.

### CODE REVIEW

**Review by GAMER-WORLD — APPROVED** [review]
So at this point we don't need to do much! Awesome!

**Review by paulinearcita — APPROVED** [review]
This looks good to me. I don't think I can suggest any changes on this. Thank you for doing this for our group!

**Review by joshkettlehake — APPROVED** [review]
OK. This looks similar to the example we saw in class. My most recent pull requests have added doxygen style comments to the code I had previously submitted. I will merge this now.

**Review by hazejjk — APPROVED** [review]
Doxyfile looks good to me! I don't think any changes is needed for this file.

**Pull request merged**
