### PR TITLE
Finished t002 for US016

### PR DESCRIPTION
**Pull request by paulinearcita**
Updated dependencies for poi, updated pom for poi dependency, created PowerPoint file and slide, added test.pptx for proof that t002 is working.

### CODE REVIEW

**Review by aminahaq305 — CHANGES_REQUESTED** [review]
Since you were having some issues with your branch and Sanyam's code being reflected in it, I would suggest merging his branch and then removing his code in your branch before having it merged

**Review by aminahaq305 — APPROVED** [review]
Looks good to me, you have made the changes necessary and updated the dependencies as requested. Just wait for your primary reviewer to merge it.

**Review by hazejjk — APPROVED** [review]
Everything looks good to me.

**Comment by hazejjk** [comment]
Closing this pull request, but will need to re-commit due to commit conflicts that has to be resolved.

**Pull request closed without merging**
