### PR TITLE
Added A new addImage Class

### PR DESCRIPTION
**Pull request by sanyam-goyal**
Added a new addImage Class

Screenshot1: Showing that the code is running without any errors
image

Screenshot2: Image is added to the pdf document
image

### CODE REVIEW

**Review by priyap2021 — CHANGES_REQUESTED** [review]
Good work! Looking at your proof, the system is not printing from where taking the inputs from user (x ,y coodinate and width)

**Comment by sanyam-goyal** [comment]
image

**Comment by sanyam-goyal** [comment]
Hi @priyap2021 I have added another screenshot which shows user inputs.

**Review by paulinearcita — CHANGES_REQUESTED** [review]
Good work Sanyam! I suggest adding a before and after of your pdf file to verify that it really inserted on the right page and right coordinates. Please add it in this pull request or if you decided to create another pull request, I can merge this and check the other pull request. Just let me know!

**Comment by sanyam-goyal** [comment]
Hi @paulinearcita 
I am attaching the screen captures in this comment 
1. Before Screenshot
image

2. After Screenshot 
image

**Comment by paulinearcita** [comment]
> Hi @paulinearcita
> I am attaching the screen captures in this comment
> 
> 1. Before Screenshot
>    image
> 2. After Screenshot
>    image

Thank you for this! I will merge this pull request now.

**Pull request merged**
