### PR TITLE
Implemented code to extract phone numbers

### PR DESCRIPTION
**Pull request by GAMER-WORLD**
Here's the proof!

### CODE REVIEW

**Comment by GAMER-WORLD** [comment]
Here's the proof!

**Comment by GAMER-WORLD** [comment]
I'm not sure why did IntelliJ edited multiple files, you don't have to merge TextEditing.java, RemovePage.java, PdfToPptx.java, ImageExtraction.java, Encryption.java, BookMarks.java

**Review by joshkettlehake — APPROVED** [review]
It is fine to mark these as completed. Is there testing to go along with the submitted code? I do not see it here.

**Comment by sanyam-goyal** [comment]
Good work.

**Pull request merged**
