### PR TITLE
Update Group5 - Backlog

### PR DESCRIPTION
**Pull request by joshkettlehake**
Updated status for sprint 1 tasks assigned to Joshua.

### CODE REVIEW

**Comment by priyap2021** [comment]
Yes This looks good. Just add the status that you completed your sprint task, so it will be easy to count the points. After that will merge to main.

**Review by aminahaq305 — APPROVED** [review]
I think things look good, really appreciate the "in review" tag.

**Review by priyap2021 — APPROVED** [review]
Approve merging these changes.

**Review by priyap2021 — COMMENTED** [review]
Even though this request is close. I wan to review it again so that it count towards my points.

Yes This looks good. Just add the status that u completed your sprint task, so it will be easy to count the points. After that will merge to main.

**Pull request merged**
