### PR TITLE
Sanyam-Goyal-Task

### PR DESCRIPTION
**Pull request by sanyam-goyal**
Added a new cass called RemovePage. It will delete the page specified by the user... 

Screenshot 1: Originally the Number Of Pages in the document equals to 3 
image

Screenshot 2: Result of the Console 
image

Screenshot 3: PDF Document after the specified Page is removed
image

### CODE REVIEW

**Review by aminahaq305 — CHANGES_REQUESTED** [review]
Everything looks good, and thank you for fixing Priya's error. We as a team need to discuss error handling, please take the lead on that in the next team meeting if possible.
As for changes, the only thing I would critique is the formatting of the comments, please watch the video on the discord information server and reformat your comments either now, or during the last sprint before we create the SDD.

**Comment by paulinearcita** [comment]
This looks good! And I was trying to look at that Encryption error. Now it's fixed! I will keep this pull request open. Please add comments in Doxygen format then I will merge this to main.

**Review by paulinearcita — CHANGES_REQUESTED** [review]
This looks good. Please add comments in your code following Doxygen file.

**Review by joshkettlehake — CHANGES_REQUESTED** [review]
The class name has to match the file name.

**Review by priyap2021 — CHANGES_REQUESTED** [review]
The reason why file name is different because I did it manually. I will make changes and update my file. Thannk You.

**Pull request merged**
