### PR TITLE
Implemented t022 and t031. Started implementation of t043.

### PR DESCRIPTION
**Pull request by hazejjk**
Implemented code for t022 and t031 for US003. I've also started coding the graphical user interface for t043.

### CODE REVIEW

**Comment by priyap2021** [comment]
This looks good to me and well deoxygen formatted as well, except provide the screenshot as proof that code is working.  Implementation of task 040 looks good too.

**Comment by hazejjk** [comment]
Proof that code works (Tested using two test PDF files):

Test2.pdf code output:

unknown1

Adobe Acrobat prints out the same:

unknown

Test.pdf code output:

unknown3

Adobe Acrobat prints out the same:

unknown2

**Comment by priyap2021** [comment]
Looks good! thank You for providing proofs.

**Review by paulinearcita — COMMENTED** [review]
This looks good! It's a very nice feature to have.  Great job!

**Review by aminahaq305 — APPROVED** [review]
Your searchString.java file looks great, the code is clean and well formatted. However you have made changes to the PdftoPptx.java file and EncryptionPDF, I'm not sure how that would affect the main. If there are no major conflicts, I will merge it.

**Review by aminahaq305 — CHANGES_REQUESTED** [review]
There are conflicts on three files, please resolve those before attempting to merge

**Review by priyap2021 — COMMENTED** [review]
I think primary reviewer won't be able to merge until conflicts issue solve.

**Comment by aminahaq305** [comment]
Closing pull request due to conlicts

**Pull request closed without merging**
