### PR TITLE
Completed us011

### PR DESCRIPTION
**Pull request by joshkettlehake**
This is the completed code for us011 (extract images from pdf). If this is used in the main branch, I will have to edit the code to accept any pdf.

### CODE REVIEW

**Comment by paulinearcita** [comment]
It looks good to me. Please add comments that follows Doxygen format,

**Comment by priyap2021** [comment]
This looks good to me. Please add comments according to Deoxygen format and proof that your code fulfills the user story requirements.

**Review by aminahaq305 — CHANGES_REQUESTED** [review]
The looks good and well-formatted, except I would say please add Doxygen formatted comments and upload screenshots as proof that your code is working.

**Review by paulinearcita — COMMENTED** [review]
This looks good to me. Please make sure to include Doxygen format for documentation.

**Review by priyap2021 — COMMENTED** [review]
This looks good to me. Please add comments according to Deoxygen format and proof that your code fulfills the user story requirements.

**Review by priyap2021 — CHANGES_REQUESTED** [review]
Waiting for you to provide the proofs for US011, so that I can merge that into main.

**Pull request merged**
