### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by priyap2021**
It will add bookmarks to my existing PDFs, so that it will be easy to navigate. 
Here are the proof..

Screenshot (7)
-----------------------------------------------------------------------------------------------------
Screenshot (10)

### CODE REVIEW

**Review by aminahaq305 — APPROVED** [review]
The code looks good, however, wait for Renish to approve and merge the branch.
The only thing that needs to be addressed is the Doxygen formatted comments which we should go over in our next meeting.

**Review by joshkettlehake — APPROVED** [review]
The code looks good, and I can see that your screenshot testing works well. I don't have any issues with this.

**Review by paulinearcita — COMMENTED** [review]
This looks good to me! Good job Priya!

**Review by hazejjk — APPROVED** [review]
Your code looks good to me! No issues at all in my end.

**Review by GAMER-WORLD — APPROVED** [review]
Looks good and thank you for the picture proofs!

**Pull request merged**
