### PR TITLE
Sanyam goyal task

### PR DESCRIPTION
**Pull request by sanyam-goyal**
Added code more friendly by allowing users to enter the x and y position coordinates where they want to place the image in the pdf.

### CODE REVIEW

**Review by priyap2021 — COMMENTED** [review]
The code looks good to me. Just deoxgen comments missing in some places.

**Review by joshkettlehake — APPROVED** [review]
The code itself looks good to me. I noticed that some of your comments have 2 slashes and some of your comments have three slashes. I am not sure the reason for this, and I just wanted to bring it to your attention. Also, It would be nice to see some screenshots of the output.

**Review by paulinearcita — COMMENTED** [review]
This change is related to your other pull request #46. I will wait for the changes I requested for that before I merge this.

**Comment by sanyam-goyal** [comment]
Hi @joshkettlehake @paulinearcita @priyap2021 
I have fixed my comments in my 2nd commit. 
Just FYI: This request was related to https://github.com/paulinearcita/CEG4110-Group5-PdfBox/pull/46.

**Pull request merged**
