### PR TITLE
Pdf to pptx class file with packages that can be used

### PR DESCRIPTION
**Pull request by paulinearcita**
I have the class file for pdf to pptx conversion and added packages that can be used. This contributes to complete Task 003.

### CODE REVIEW

**Comment by aminahaq305** [comment]
The syntax and formatting look good, just ensure that when you start coding the rest of the program you use the same branch for your commits.

**Review by hazejjk — COMMENTED** [review]
Looks good to me.

**Review by hazejjk — COMMENTED** [review]
This is looking good!

**Review by aminahaq305 — COMMENTED** [review]
The syntax and formatting look good, just ensure that when you start coding the rest of the program you use the same branch for your commits.
Also one thing I noticed which Sanyam pointed out, your code contains poi library, you need to import that and update the maven dependencies

**Pull request merged**
