### PR TITLE
Completed task 030

### PR DESCRIPTION
**Pull request by priyap2021**
This code provide the security to PDFs.  Please review and let me know.

### CODE REVIEW

**Comment by aminahaq305** [comment]
Please provide proof that your code fulfills your User Story requirements. Also, ensure that you comment fully on the capability of your class as you have done for each line of code, so that doxygen formatting is embedded as you code.
Also, is the key hardcoded and random? What kind of encryption is this function implementing? Will there be decryption capabilities as well?

**Comment by sanyam-goyal** [comment]
Hi @priyap2021, 
Could you please attach a test case and a screen capture of how your code actually works ? 
Apart from that if we increase the length of the encryption key will it improve the level of encryption or it won't make much difference? If it does make a significant difference then should we increase the length of encryption key to 256 instead of 128. 
Let me know how you feel about this 

Thank you,
Sanyam Goyal

**Review by GAMER-WORLD — APPROVED** [review]
Code looks pretty clean and well commented. As we were talking earlier, the code needs proof that it's working.

**Review by aminahaq305 — COMMENTED** [review]
Please provide proof that your code fulfills your User Story requirements. Also, ensure that you comment fully on the capability of your class as you have done for each line of code, so that doxygen formatting is embedded as you code.
Also, is the key hardcoded and random? What kind of encryption is this function implementing? Will there be decryption capabilities as well?
Also, your file is named EncryptionPDF while your class is named Encryption

**Comment by priyap2021** [comment]
Actually I have added my java class manually, so unknowing file name is different. The "key" is the random name that i chose to initialized and set my length of the encryption key. I think 128 bits is sufficient for security. I will make changes on the comments so the dioxygen formatting. Should I make another pull request for the proof and the changes I make now since it is already merged?? @aminahaq305

**Pull request merged**
